[package]
name = "tree-sitter-duat-text"
description = "Parsing for string literals in the text! family of macros from Duat"
version = "0.1.0"
authors = ["AhoyISki <ahoyiski@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "duat-text"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "https://github.com/ahoyiski/tree-sitter-duat-text"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.25.3"
