/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 30
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_raw_sequence = 1,
  sym_quote_escape = 2,
  sym_ascii_escape = 3,
  sym_unicode_escape = 4,
  sym_string_continue = 5,
  sym_argument_delimiter_escape = 6,
  anon_sym_LBRACE = 7,
  anon_sym_COLON = 8,
  anon_sym_RBRACE = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  anon_sym_DOT = 12,
  sym_identifier = 13,
  sym_modifier = 14,
  sym_source_file = 15,
  sym__str_literal = 16,
  sym_expr_argument = 17,
  sym_form_argument = 18,
  sym_identifiers = 19,
  aux_sym_source_file_repeat1 = 20,
  aux_sym_identifiers_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_raw_sequence] = "raw_sequence",
  [sym_quote_escape] = "quote_escape",
  [sym_ascii_escape] = "ascii_escape",
  [sym_unicode_escape] = "unicode_escape",
  [sym_string_continue] = "string_continue",
  [sym_argument_delimiter_escape] = "argument_delimiter_escape",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COLON] = ":",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DOT] = ".",
  [sym_identifier] = "identifier",
  [sym_modifier] = "modifier",
  [sym_source_file] = "source_file",
  [sym__str_literal] = "_str_literal",
  [sym_expr_argument] = "expr_argument",
  [sym_form_argument] = "form_argument",
  [sym_identifiers] = "identifiers",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_identifiers_repeat1] = "identifiers_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_raw_sequence] = sym_raw_sequence,
  [sym_quote_escape] = sym_quote_escape,
  [sym_ascii_escape] = sym_ascii_escape,
  [sym_unicode_escape] = sym_unicode_escape,
  [sym_string_continue] = sym_string_continue,
  [sym_argument_delimiter_escape] = sym_argument_delimiter_escape,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_identifier] = sym_identifier,
  [sym_modifier] = sym_modifier,
  [sym_source_file] = sym_source_file,
  [sym__str_literal] = sym__str_literal,
  [sym_expr_argument] = sym_expr_argument,
  [sym_form_argument] = sym_form_argument,
  [sym_identifiers] = sym_identifiers,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_identifiers_repeat1] = aux_sym_identifiers_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_quote_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_ascii_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_unicode_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_string_continue] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_delimiter_escape] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__str_literal] = {
    .visible = false,
    .named = true,
  },
  [sym_expr_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_form_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_identifiers] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifiers_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        ' ', 5,
        '.', 35,
        ':', 29,
        '[', 32,
        '\\', 1,
        ']', 34,
        '{', 28,
        '}', 31,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == ' ') ADVANCE(3);
      if (lookahead == '0') ADVANCE(2);
      if (lookahead == 'u') ADVANCE(7);
      if (lookahead == 'x') ADVANCE(16);
      if (lookahead == '\'' ||
          lookahead == '\\') ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == 'n') ADVANCE(2);
      if (lookahead == 'r') ADVANCE(2);
      if (lookahead == 't') ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == ':') ADVANCE(29);
      if (lookahead == ']') ADVANCE(33);
      if (lookahead == '}') ADVANCE(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 5:
      if (lookahead == '\\') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == ']') ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == '{') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == '}') ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == '}') ADVANCE(25);
      END_STATE();
    case 10:
      if (lookahead == '}') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == '}') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == '}') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == '}') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(23);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(17);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      if (lookahead == ' ') ADVANCE(21);
      if (lookahead == '[') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead == ']') ADVANCE(6);
      if (lookahead == '{') ADVANCE(28);
      if (lookahead == '}') ADVANCE(8);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_raw_sequence);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_raw_sequence);
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_quote_escape);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_ascii_escape);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_unicode_escape);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_string_continue);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_argument_delimiter_escape);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(27);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead == '}') ADVANCE(27);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '[') ADVANCE(27);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      if (lookahead == ']') ADVANCE(27);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_modifier);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(37);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 19},
  [2] = {.lex_state = 19},
  [3] = {.lex_state = 19},
  [4] = {.lex_state = 19},
  [5] = {.lex_state = 19},
  [6] = {.lex_state = 19},
  [7] = {.lex_state = 19},
  [8] = {.lex_state = 19},
  [9] = {.lex_state = 19},
  [10] = {.lex_state = 19},
  [11] = {.lex_state = 19},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 37},
  [21] = {.lex_state = 37},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 37},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 37},
  [29] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_quote_escape] = ACTIONS(1),
    [sym_ascii_escape] = ACTIONS(1),
    [sym_unicode_escape] = ACTIONS(1),
    [sym_string_continue] = ACTIONS(1),
    [sym_argument_delimiter_escape] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(22),
    [sym__str_literal] = STATE(2),
    [sym_expr_argument] = STATE(2),
    [sym_form_argument] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_raw_sequence] = ACTIONS(5),
    [sym_quote_escape] = ACTIONS(7),
    [sym_ascii_escape] = ACTIONS(7),
    [sym_unicode_escape] = ACTIONS(7),
    [sym_string_continue] = ACTIONS(7),
    [sym_argument_delimiter_escape] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym__str_literal] = STATE(3),
    [sym_expr_argument] = STATE(3),
    [sym_form_argument] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_raw_sequence] = ACTIONS(15),
    [sym_quote_escape] = ACTIONS(17),
    [sym_ascii_escape] = ACTIONS(17),
    [sym_unicode_escape] = ACTIONS(17),
    [sym_string_continue] = ACTIONS(17),
    [sym_argument_delimiter_escape] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym__str_literal] = STATE(3),
    [sym_expr_argument] = STATE(3),
    [sym_form_argument] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_raw_sequence] = ACTIONS(21),
    [sym_quote_escape] = ACTIONS(24),
    [sym_ascii_escape] = ACTIONS(24),
    [sym_unicode_escape] = ACTIONS(24),
    [sym_string_continue] = ACTIONS(24),
    [sym_argument_delimiter_escape] = ACTIONS(24),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(30),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(35), 3,
      sym_raw_sequence,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(33), 6,
      ts_builtin_sym_end,
      sym_quote_escape,
      sym_ascii_escape,
      sym_unicode_escape,
      sym_string_continue,
      sym_argument_delimiter_escape,
  [14] = 2,
    ACTIONS(39), 3,
      sym_raw_sequence,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(37), 6,
      ts_builtin_sym_end,
      sym_quote_escape,
      sym_ascii_escape,
      sym_unicode_escape,
      sym_string_continue,
      sym_argument_delimiter_escape,
  [28] = 2,
    ACTIONS(43), 3,
      sym_raw_sequence,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(41), 6,
      ts_builtin_sym_end,
      sym_quote_escape,
      sym_ascii_escape,
      sym_unicode_escape,
      sym_string_continue,
      sym_argument_delimiter_escape,
  [42] = 2,
    ACTIONS(47), 3,
      sym_raw_sequence,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(45), 6,
      ts_builtin_sym_end,
      sym_quote_escape,
      sym_ascii_escape,
      sym_unicode_escape,
      sym_string_continue,
      sym_argument_delimiter_escape,
  [56] = 2,
    ACTIONS(51), 3,
      sym_raw_sequence,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(49), 6,
      ts_builtin_sym_end,
      sym_quote_escape,
      sym_ascii_escape,
      sym_unicode_escape,
      sym_string_continue,
      sym_argument_delimiter_escape,
  [70] = 2,
    ACTIONS(55), 3,
      sym_raw_sequence,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(53), 6,
      ts_builtin_sym_end,
      sym_quote_escape,
      sym_ascii_escape,
      sym_unicode_escape,
      sym_string_continue,
      sym_argument_delimiter_escape,
  [84] = 2,
    ACTIONS(59), 3,
      sym_raw_sequence,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(57), 6,
      ts_builtin_sym_end,
      sym_quote_escape,
      sym_ascii_escape,
      sym_unicode_escape,
      sym_string_continue,
      sym_argument_delimiter_escape,
  [98] = 2,
    ACTIONS(63), 3,
      sym_raw_sequence,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(61), 6,
      ts_builtin_sym_end,
      sym_quote_escape,
      sym_ascii_escape,
      sym_unicode_escape,
      sym_string_continue,
      sym_argument_delimiter_escape,
  [112] = 3,
    ACTIONS(67), 1,
      anon_sym_DOT,
    STATE(14), 1,
      aux_sym_identifiers_repeat1,
    ACTIONS(65), 3,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [124] = 3,
    ACTIONS(71), 1,
      anon_sym_DOT,
    STATE(13), 1,
      aux_sym_identifiers_repeat1,
    ACTIONS(69), 3,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [136] = 3,
    ACTIONS(67), 1,
      anon_sym_DOT,
    STATE(13), 1,
      aux_sym_identifiers_repeat1,
    ACTIONS(74), 3,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [148] = 4,
    ACTIONS(76), 1,
      anon_sym_COLON,
    ACTIONS(78), 1,
      anon_sym_RBRACE,
    ACTIONS(80), 1,
      sym_identifier,
    STATE(19), 1,
      sym_identifiers,
  [161] = 4,
    ACTIONS(80), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_COLON,
    ACTIONS(84), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      sym_identifiers,
  [174] = 1,
    ACTIONS(69), 4,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [181] = 2,
    ACTIONS(86), 1,
      anon_sym_COLON,
    ACTIONS(88), 1,
      anon_sym_RBRACK,
  [188] = 2,
    ACTIONS(90), 1,
      anon_sym_COLON,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
  [195] = 1,
    ACTIONS(94), 1,
      sym_modifier,
  [199] = 1,
    ACTIONS(96), 1,
      sym_modifier,
  [203] = 1,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
  [207] = 1,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
  [211] = 1,
    ACTIONS(102), 1,
      sym_identifier,
  [215] = 1,
    ACTIONS(104), 1,
      anon_sym_RBRACK,
  [219] = 1,
    ACTIONS(106), 1,
      sym_modifier,
  [223] = 1,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
  [227] = 1,
    ACTIONS(110), 1,
      sym_modifier,
  [231] = 1,
    ACTIONS(112), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 14,
  [SMALL_STATE(6)] = 28,
  [SMALL_STATE(7)] = 42,
  [SMALL_STATE(8)] = 56,
  [SMALL_STATE(9)] = 70,
  [SMALL_STATE(10)] = 84,
  [SMALL_STATE(11)] = 98,
  [SMALL_STATE(12)] = 112,
  [SMALL_STATE(13)] = 124,
  [SMALL_STATE(14)] = 136,
  [SMALL_STATE(15)] = 148,
  [SMALL_STATE(16)] = 161,
  [SMALL_STATE(17)] = 174,
  [SMALL_STATE(18)] = 181,
  [SMALL_STATE(19)] = 188,
  [SMALL_STATE(20)] = 195,
  [SMALL_STATE(21)] = 199,
  [SMALL_STATE(22)] = 203,
  [SMALL_STATE(23)] = 207,
  [SMALL_STATE(24)] = 211,
  [SMALL_STATE(25)] = 215,
  [SMALL_STATE(26)] = 219,
  [SMALL_STATE(27)] = 223,
  [SMALL_STATE(28)] = 227,
  [SMALL_STATE(29)] = 231,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_form_argument, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_form_argument, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_argument, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr_argument, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_form_argument, 4, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_form_argument, 4, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_form_argument, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_form_argument, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_argument, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr_argument, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_argument, 4, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr_argument, 4, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_argument, 5, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr_argument, 5, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_form_argument, 5, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_form_argument, 5, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifiers, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identifiers_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_identifiers_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifiers, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [98] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_duat_text(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "duat_text",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
